<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="8" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-27T17:48:56 CEST" name="TestNG" finished-at="2023-10-27T17:49:44 CEST" duration-ms="47357">
    <groups>
      <group name="Regression">
        <method signature="LoginWithDP.readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromArray" class="FrontEnd.SauceDemo.LoginWithDP"/>
        <method signature="LoginWithDP.readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromFileCSVLike" class="FrontEnd.SauceDemo.LoginWithDP"/>
        <method signature="LoginWithDP.readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromFileExcel" class="FrontEnd.SauceDemo.LoginWithDP"/>
      </group> <!-- Regression -->
      <group name="Smoke">
        <method signature="LoginWithDP.readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromArray" class="FrontEnd.SauceDemo.LoginWithDP"/>
        <method signature="LoginWithDP.readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromFileCSVLike" class="FrontEnd.SauceDemo.LoginWithDP"/>
        <method signature="LoginWithDP.readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" name="readFromFileExcel" class="FrontEnd.SauceDemo.LoginWithDP"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2023-10-27T17:48:56 CEST" name="TestNG" finished-at="2023-10-27T17:49:44 CEST" duration-ms="47357">
      <class name="FrontEnd.SauceDemo.LoginWithDP">
        <test-method signature="readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:03 CEST" name="readFromArray" description="Trying to read data from an array object" data-provider="array" finished-at="2023-10-27T17:49:08 CEST" duration-ms="4837" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [fasdfads] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [fasdfads] but found [Swag Labs]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at helpers.AssertionsList.assertAll(AssertionsList.java:41)
at FrontEnd.SauceDemo.LoginWithDP.readFromArray(LoginWithDP.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromArray -->
        <test-method signature="readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:09 CEST" name="readFromArray" description="Trying to read data from an array object" data-provider="array" finished-at="2023-10-27T17:49:11 CEST" duration-ms="2187" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [fasdfads] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [fasdfads] but found [Swag Labs]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at helpers.AssertionsList.assertAll(AssertionsList.java:41)
at FrontEnd.SauceDemo.LoginWithDP.readFromArray(LoginWithDP.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromArray -->
        <test-method signature="readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:11 CEST" name="readFromArray" description="Trying to read data from an array object" data-provider="array" finished-at="2023-10-27T17:49:13 CEST" duration-ms="1910" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at helpers.AssertionsList.assertAll(AssertionsList.java:41)
at FrontEnd.SauceDemo.LoginWithDP.readFromArray(LoginWithDP.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromArray -->
        <test-method signature="readFromArray(java.lang.String,java.lang.String)[pri:100, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:13 CEST" name="readFromArray" description="Trying to read data from an array object" data-provider="array" finished-at="2023-10-27T17:49:20 CEST" duration-ms="7254" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs],
expected [fasdfads] but found [Swag Labs]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at helpers.AssertionsList.assertAll(AssertionsList.java:41)
at FrontEnd.SauceDemo.LoginWithDP.readFromArray(LoginWithDP.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromArray -->
        <test-method signature="readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:24 CEST" name="readFromFileExcel" description="Trying to read data from an Excel file" data-provider="excel" finished-at="2023-10-27T17:49:26 CEST" duration-ms="1691" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileExcel -->
        <test-method signature="readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:26 CEST" name="readFromFileExcel" description="Trying to read data from an Excel file" data-provider="excel" finished-at="2023-10-27T17:49:28 CEST" duration-ms="1594" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileExcel -->
        <test-method signature="readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:28 CEST" name="readFromFileExcel" description="Trying to read data from an Excel file" data-provider="excel" finished-at="2023-10-27T17:49:29 CEST" duration-ms="1481" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234.0]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1324.0]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileExcel -->
        <test-method signature="readFromFileExcel(java.lang.String,java.lang.String)[pri:300, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:30 CEST" name="readFromFileExcel" description="Trying to read data from an Excel file" data-provider="excel" finished-at="2023-10-27T17:49:31 CEST" duration-ms="1525" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[1234admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileExcel -->
        <test-method signature="readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:31 CEST" name="readFromFileCSVLike" description="Trying to read data from a CSV-like file" data-provider="csv" finished-at="2023-10-27T17:49:33 CEST" duration-ms="1469" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileCSVLike -->
        <test-method signature="readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:33 CEST" name="readFromFileCSVLike" description="Trying to read data from a CSV-like file" data-provider="csv" finished-at="2023-10-27T17:49:35 CEST" duration-ms="1422" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[locked_out_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileCSVLike -->
        <test-method signature="readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:35 CEST" name="readFromFileCSVLike" description="Trying to read data from a CSV-like file" data-provider="csv" finished-at="2023-10-27T17:49:36 CEST" duration-ms="1470" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[problem_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileCSVLike -->
        <test-method signature="readFromFileCSVLike(java.lang.String,java.lang.String)[pri:400, instance:FrontEnd.SauceDemo.LoginWithDP@5b04476e]" started-at="2023-10-27T17:49:37 CEST" name="readFromFileCSVLike" description="Trying to read data from a CSV-like file" data-provider="csv" finished-at="2023-10-27T17:49:43 CEST" duration-ms="6478" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[performance_glitch_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromFileCSVLike -->
      </class> <!-- FrontEnd.SauceDemo.LoginWithDP -->
    </test> <!-- TestNG -->
  </suite> <!-- TestNG -->
</testng-results>
